services:
  postgres:
    image: postgres:17
    container_name: barber-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - barber-pgdata:/var/lib/postgresql/data

volumes:
  barber-pgdata:
